### ISSUE TITLE
Migration no longer works

### ISSUE THREAD

**Issue by MrMusic** [JoomGalleryfriends/JG4-dev#253]
With the current main branch, the following error occurs when starting the image migration:

```
[Error] count(): Argument #1 ($value) must be of type Countable|array, int given

#0 ...administrator\components\com_joomgallery\src\Model\MigrationModel.php(1260): Joomgallery\Component\Joomgallery\Administrator\Helper\JoomHelper::getService('FileManager', 2) 
#1 ...administrator\components\com_joomgallery\src\Model\MigrationModel.php(812): Joomgallery\Component\Joomgallery\Administrator\Model\MigrationModel->deleteRecord('image', 1) 
#2 ...administrator\components\com_joomgallery\src\Controller\MigrationController.php(770): Joomgallery\Component\Joomgallery\Administrator\Model\MigrationModel->migrate('image', 1)
```

and the migration script cannot be continued.

DE: 
Mit dem aktuellen main-Branch kommt es beim starten der Bilder-Migration es zu folgendem Fehler:

```
[Error] count(): Argument #1 ($value) must be of type Countable|array, int given

#0 ...administrator\components\com_joomgallery\src\Model\MigrationModel.php(1260): Joomgallery\Component\Joomgallery\Administrator\Helper\JoomHelper::getService('FileManager', 2) 
#1 ...administrator\components\com_joomgallery\src\Model\MigrationModel.php(812): Joomgallery\Component\Joomgallery\Administrator\Model\MigrationModel->deleteRecord('image', 1) 
#2 ...administrator\components\com_joomgallery\src\Controller\MigrationController.php(770): Joomgallery\Component\Joomgallery\Administrator\Model\MigrationModel->migrate('image', 1)
```

und das Migrationsskript kann nicht mehr fortgesetzt werden.

**Comment by MrMusic** [comment]
Fixed with https://github.com/JoomGalleryfriends/JG4-dev/pull/258
